version: 2.1

jobs:
  build:
    docker:
      - image: ruby
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"

workflows:
  say-hello-workflow:
    jobs:
      - build
