FROM node:latest

ARG UNAME=devuser
ARG UID=1000
ARG GID=1000
RUN groupadd -g $GID -o $UNAME
RUN useradd -m -u $UID -g $GID -o -s /bin/bash $UNAME


ENV NODE_ENV=development
WORKDIR /usr/src

# Set the yarn.lock and install packages
#
# since we cant use bind mounts for circleci images
COPY ./fe_app .

#to avoid overwrites from volume bind with docker-compose, copy into root folder
COPY ./docker/entrypoints/fe.sh /tmp/docker-fe-entrypoint.sh

#COPY ./package.json /usr/src/package.json

#COPY ./ssh /root/.ssh
#RUN chmod -R 700 /root/.ssh
#ENV GIT_SSH_COMMAND='ssh -i /root/.ssh/id_rsa'

RUN ["chmod", "+x", "/tmp/docker-fe-entrypoint.sh"]

ENTRYPOINT ["/tmp/docker-fe-entrypoint.sh"]

COPY ./docker/entrypoints/test.sh /tmp/docker-test-entrypoint.sh
RUN ["chmod", "+x", "/tmp/docker-test-entrypoint.sh"]



USER $UNAME
