FROM bubbam2006/cypress:latest

ARG UNAME=testuser
ARG UID=1000
ARG GID=1000
RUN groupadd -g $GID -o $UNAME
RUN useradd -m -u $UID -g $GID -o -s /bin/bash $UNAME

#to avoid overwrites from volume bind with docker-compose, copy into root folder
COPY ./docker/entrypoints/cypress_bash.sh /tmp/docker-cypress-bash-entrypoint.sh

RUN ["chmod", "+x", "/tmp/docker-cypress-bash-entrypoint.sh"]

USER $UNAME

