FROM bubbam2006/cypress:latest

ARG UNAME=testuser
ARG UID=1000
ARG GID=1000
RUN groupadd -g $GID -o $UNAME
RUN useradd -m -u $UID -g $GID -o -s /bin/bash $UNAME

WORKDIR /usr/src

#to avoid overwrites from volume bind with docker-compose, copy into root folder
COPY ./docker/entrypoints/cypress_bash.sh /tmp/docker-cypress-bash-entrypoint.sh

RUN ["chmod", "+x", "/tmp/docker-cypress-bash-entrypoint.sh"]


COPY ./docker/entrypoints/test.sh /tmp/docker-test-entrypoint.sh
RUN ["chmod", "+x", "/tmp/docker-test-entrypoint.sh"]

# run as root, solve some problems binding to docker socket and the /usr/src folder being owned by root!
#USER $UNAME


COPY ./cypress .


