development:
  cloud_name: "dbz4fttfa"
  api_key: "683659755124933"
  api_secret: "AHyTLsjktZig6isMZROEg3VUQhg"
  secure: true

production:
  cloud_name: "dbz4fttfa"
  api_key: "683659755124933"
  api_secret: "AHyTLsjktZig6isMZROEg3VUQhg"
  secure: true
